notifications:
  webhooks: https://coveralls.io/webhook

env:
  global:
    - COVERALLS_PARALLEL=true

matrix:
  include:
  - name: "Middleware Tests"
    language: java
    jdk: oraclejdk8
    before_script:
      - cd middleware
    script:
      - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn clean test cobertura:cobertura jacoco:report
    after_success:
      - mvn coveralls:report -DserviceName="travis-ci" -DserviceBuildNumber=$TRAVIS_BUILD_ID

  - name: "UI Tests"
    language: node_js
    node_js: "8"
    addons:
      chrome: stable
    before_install:
      - cd ui
    install:
      - yarn install
    before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sleep 3 # give xvfb some time to start
    script:
      - yarn test:ci
    after_success:
      - yarn test:report
