version: '3'
services:
  solr:
    build: ./solr 
    ports:
    - "8983:8983"
  middleware:
    build: ./middleware
    volumes:
     - ./middleware:/app
     #https://github.com/chanezon/docker-tips/blob/master/java-build-mount-maven-repo.md
     - $HOME/.m2:/root/.m2
    command: ["mvn", "spring-boot:run"]
    ports:
     - "4000:9000"
    links:
     - solr
     - mariadb
  mariadb:
    image: mariadb
    ports:
      - "3388:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hello
      - MYSQL_USER=vivodev
      - MYSQL_PASSWORD=local_vivo_work
      - MYSQL_DATABASE=new_dev_vivo
    volumes:  # Mount relative path source folder on host to path docker container
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # usage:
  # docker-compose build middleware
  # docker-compose run middleware bash
  # docker-compose up
